export const AUTH = {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    SESSION_LOGIN: 'SESSION_LOGIN',
    UPDATE: "UPDATE",
}

export const PROJECT = {
    LOAD_START: "LOAD_START",
    CLEAN: "CLEAN",
    LOAD_SUCCESS: "LOAD_SUCCESS",
    LOAD_FAIL: "LOAD_FAIL",
    UPDATE: "UPDATE",
    ADD_TASK: 'ADD_TASK',
    ADD_GROUP: 'ADD_GROUP',
    ADD_USER: 'ADD_USER',
}