export const AUTH = {
    LOGIN_START: 'AUTH_LOGIN_START',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
    LOGOUT: 'AUTH_LOGOUT',
    SESSION_LOGIN: 'AUTH_SESSION_LOGIN',
    UPDATE: "AUTH_UPDATE",
    CLEAR_STATUS: 'AUTH_CLEAR_STATUS',
}

export const PROJECT = {
    LOAD_START: "PROJECT_LOAD_START",
    CLEAN: "PROJECT_CLEAN",
    LOAD_SUCCESS: "PROJECT_LOAD_SUCCESS",
    LOAD_FAIL: "PROJECT_LOAD_FAIL",
    UPDATE_START: 'PROJECT_UPDATE_START',
    UPDATED: "PROJECT_UPDATED",
    ADD_FAIL: 'PROJECT_ADD_FAIL',
    ADD_TASK: 'PROJECT_ADD_TASK',
    ADD_GROUP: 'PROJECT_ADD_GROUP',
    ADD_USER: 'PROJECT_ADD_USER',
    CLEAR_STATUS: 'PROJECT_CLEAR_STATUS',
}